[package]
name = "fixedfloat-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
hmac = "0.12.1"
qrcode = "0.12.0"
serde_json = "1.0.91"
sha2 = "0.10.6"
ureq = "2.6.2"
